### ISSUE TITLE
Make input compatible with the output from Raw_CleanUp.R

### ISSUE THREAD

**Issue by matiasandina** [matiasandina/USV-Interpolation-CleanUp#2]
Previous project produces an output that is now incompatible, update functions to account for that.

Check column names, columns that have been added are for sure

("unique.id"  "file.name"  "label"      "duration"   "start.time")

**Comment by matiasandina** [comment]
Also, this input should be fed from the output of the previous pipeline step (directly from the URL)? can you see a case in which this is not a good idea @ituncali ?

**Comment by matiasandina** [comment]
On sourcing

Scripts
https://gist.github.com/fernandomayer/6158625

Data, readr for delimited files ?
https://stackoverflow.com/questions/14441729/read-a-csv-from-github-into-r

**Comment by ituncali** [comment]
Maybe it wouldn't be a good idea if I want to run different sets of data through the workflow? What if I have multiple outputs from the first Raw_CleanUp or I change something? Will it be storing all of the outputs in the same folder (same URL)?
